# Generated by Django 4.2.15 on 2025-01-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oprogreso', '0002_tema_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='orden',
            field=models.IntegerField(default=0),
        ),
    ]
