# Generated by Django 4.2.15 on 2025-01-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oprogreso', '0003_tema_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='logro',
            name='puntos_necesarios',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='logro',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
