# Generated by Django 4.2.15 on 2025-01-12 13:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oprogreso', '0005_logro_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='contenido',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
