# Generated by Django 4.2.15 on 2025-01-19 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oprogreso', '0006_alter_tema_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
