# Generated by Django 4.2.15 on 2025-02-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oprogreso', '0007_alter_actividad_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='repetible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actividad',
            name='veces_realizada',
            field=models.IntegerField(default=0),
        ),
    ]
